'use client';
import {useEffect,useState} from 'react';
import {Shirt,ScanLine,ArrowUpRight,Download,Copy,RefreshCw} from 'lucide-react';
import {SalesHeader,SalesFooter} from '../sales/shell';
import {garments,validSession,type TrackEvent} from '../sales/catalog';
export default function Demo(){const [session,setSession]=useState('');const [selected,setSelected]=useState<string>(garments[0].id);const [events,setEvents]=useState<TrackEvent[]>([]);const [qr,setQr]=useState('');const [link,setLink]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [loaded,setLoaded]=useState(false);const [synced,setSynced]=useState('');
useEffect(()=>{const url=new URL(location.href);const existing=url.searchParams.get('session');const id=existing&&validSession(existing)?existing:crypto.randomUUID();url.searchParams.set('session',id);history.replaceState(null,'',url);setSession(id)},[]);
useEffect(()=>{if(!session)return;let alive=true;const controller=new AbortController();async function poll(){try{const r=await fetch('/api/demo?session='+encodeURIComponent(session),{cache:'no-store',signal:controller.signal});const data=await r.json() as {events:TrackEvent[];error?:string};if(!r.ok)throw Error(data.error||'Tracking is unavailable.');if(alive){setEvents(data.events);setError('');setLoaded(true);setSynced(new Date().toLocaleTimeString())}}catch(e){if(alive&&!(e instanceof DOMException&&e.name==='AbortError')){setError('Unable to refresh tracking. Check your connection; the page will retry.');setLoaded(true)}}}void poll();const timer=setInterval(poll,5000);return()=>{alive=false;controller.abort();clearInterval(timer)}},[session]);
useEffect(()=>{if(!session)return;let alive=true;setQr('');const url=location.origin+'/scan/'+session+'/'+selected;setLink(url);import('qrcode').then(q=>q.toDataURL(url,{width:600,margin:4,color:{dark:'#000000',light:'#ffffff'}})).then(s=>{if(alive)setQr(s)}).catch(()=>{if(alive)setNotice('QR generation failed. Use the check-in link below.')});return()=>{alive=false}},[session,selected]);
const product=garments.find(p=>p.id===selected)!;const filtered=events.filter(e=>e.product===selected);
async function copy(){try{await navigator.clipboard.writeText(link);setNotice('Check-in link copied. Open it on another device.')}catch{setNotice('Copy is unavailable in this browser. Select and copy the visible link below.')}}
function download(){const blob=new Blob([JSON.stringify({session,products:garments,events},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='loompass-demo-events.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Tracking export downloaded.')}
return <div className="sales"><SalesHeader/><main className="sales-page"><div className="sales-kicker">LIVE PROTOTYPE / SCAN & TRACK</div><h1>Give a garment<br/>its next checkpoint.</h1><p>Choose a sample product. Scan its QR with another phone. Confirm a check-in and watch it appear here.</p><div className="demo-note">Demonstration data only. Check-ins are user-submitted events, not proof of authenticity, physical location or delivery. Your session is shared by link.</div><div className="demo-toolbar"><span className="live-indicator">{synced?'Last synced '+synced:'Connecting to shared tracking…'}</span><div className="sales-actions"><button className="sales-button" onClick={download} disabled={!loaded||!!error}><Download size={16}/>Export history</button><a className="sales-button" href="/demo"><RefreshCw size={16}/>New demo session</a></div></div>
<div className="demo-products" role="group" aria-label="Choose a sample garment">{garments.map(p=><button key={p.id} className={'demo-product '+(selected===p.id?'active':'')} aria-pressed={selected===p.id} onClick={()=>{setSelected(p.id);setNotice('')}}><Shirt size={32}/><span><strong>{p.name}</strong><small>{p.id} · {p.category}</small></span></button>)}</div>
<div className="demo-columns"><section className="demo-box"><div className="sales-kicker">{product.category} / SAMPLE RECORD</div><h2>{product.name}</h2><dl className="product-facts">{[['Style / batch',product.sku+' / '+product.batch],['Composition',product.composition],['Manufactured in',product.origin],['Order quantity',product.quantity],['Fabric',product.weight],['Sample size / colour',product.size+' / '+product.color]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="qr-panel">{qr?<img src={qr} width={180} height={180} alt={'Scannable QR for '+product.name}/>:<p role="status">Preparing the QR…</p>}<div><h3>Open your phone camera.</h3><p>Scan this code, choose a checkpoint and confirm. This screen refreshes every five seconds.</p>{qr&&<a className="text-link" href={qr} download={selected+'-qr.png'}><Download size={16}/>Download QR label</a>}</div></div><div className="sales-actions"><a className="sales-button dark" href={link||'#'} aria-disabled={!link}>Open check-in <ArrowUpRight size={16}/></a><button className="sales-button" onClick={copy} disabled={!link}><Copy size={16}/>Copy link</button></div>{link&&<p className="qr-link">{link}</p>}{notice&&<p className="form-message" role="status">{notice}</p>}<p className="sales-micro">Save this dashboard URL to return to the same session. No personal details are required to check in.</p></section>
<section className="demo-box"><div className="demo-toolbar"><h2>Tracking history</h2><span className="sales-kicker">{filtered.length} EVENTS</span></div><p className="sales-micro">For {product.id} · newest first · times shown on this device</p>{error&&<p role="alert" className="error-panel">{error}</p>}{!loaded?<p role="status">Loading saved checkpoints…</p>:filtered.length?<ol className="tracking-list" aria-live="polite">{filtered.map(e=><li key={e.id}><span className="event-dot"/><div><strong>{e.checkpoint}</strong><time dateTime={e.createdAt}>{new Date(e.createdAt).toLocaleString()}</time><p>{e.product} · Demo check-in</p></div></li>)}</ol>:<div className="tracking-empty"><ScanLine size={32}/><h3>The next scan starts the story.</h3><p>No check-ins in this session yet. Scan the product QR and confirm a checkpoint to begin.</p></div>}<div className="demo-note"><strong>The sample handover</strong><br/>Factory QC → Packing → Dispatch → Buyer received<br/>Each selection records an event. Checkpoints can be repeated for demonstrations.</div><a href="/resources#demo" className="text-link">Read the two-device guide →</a></section></div></main><SalesFooter/></div>}

