'use client';
import {useEffect,useMemo,useState} from 'react';
import {Shirt,ScanLine,ArrowUpRight,Download,Copy,RefreshCw} from 'lucide-react';
import {SalesHeader,SalesFooter} from '../sales/shell';
import {garments as sampleGarments,validSession,type DemoGarment,type TrackEvent} from '../sales/catalog';

export default function Demo(){
 const [session,setSession]=useState('');
 const [products,setProducts]=useState<DemoGarment[]>(sampleGarments);
 const [selected,setSelected]=useState(sampleGarments[0].id);
 const [events,setEvents]=useState<TrackEvent[]>([]);
 const [qr,setQr]=useState('');
 const [link,setLink]=useState('');
 const [error,setError]=useState('');
 const [notice,setNotice]=useState('');
 const [loaded,setLoaded]=useState(false);
 const [synced,setSynced]=useState('');
 const product=useMemo(()=>products.find(item=>item.id===selected)||products[0],[products,selected]);

 useEffect(()=>{const url=new URL(location.href);const existing=url.searchParams.get('session');const id=existing&&validSession(existing)?existing:crypto.randomUUID();url.searchParams.set('session',id);history.replaceState(null,'',url);setSession(id)},[]);
 useEffect(()=>{let active=true;fetch('/api/demo-products',{cache:'no-store'}).then(async response=>response.ok?await response.json() as {products?:DemoGarment[]}:null).then(data=>{if(!active||!data?.products?.length)return;setProducts([...data.products,...sampleGarments]);setSelected(data.products[0].id);setNotice('Your newest workspace product is ready as a sanitized demo record.')}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{if(!session)return;let alive=true;const controller=new AbortController();async function poll(){try{const response=await fetch('/api/demo?session='+encodeURIComponent(session),{cache:'no-store',signal:controller.signal});const data=await response.json() as {events:TrackEvent[];error?:string};if(!response.ok)throw Error(data.error||'Tracking is unavailable.');if(alive){setEvents(data.events);setError('');setLoaded(true);setSynced(new Date().toLocaleTimeString())}}catch(cause){if(alive&&!(cause instanceof DOMException&&cause.name==='AbortError')){setError('Unable to refresh tracking. Check your connection; the page will retry.');setLoaded(true)}}}void poll();const timer=setInterval(poll,5000);return()=>{alive=false;controller.abort();clearInterval(timer)}},[session]);
 useEffect(()=>{if(!session||!product)return;let alive=true;setQr('');const url=new URL('/scan/'+session+'/'+product.id,location.origin);if(product.workspace)url.searchParams.set('p',JSON.stringify(product));const productLink=url.toString();setLink(productLink);import('qrcode').then(module=>module.toDataURL(productLink,{width:600,margin:4,color:{dark:'#17231e',light:'#fffaf0'}})).then(source=>{if(alive)setQr(source)}).catch(()=>{if(alive)setNotice('QR generation failed. Use the check-in link below.')});return()=>{alive=false}},[session,product]);
 const filtered=events.filter(event=>event.product===selected);
 function copy(){navigator.clipboard.writeText(link).then(()=>setNotice('Check-in link copied.')).catch(()=>setNotice('Copy failed. Select the link below instead.'))}
 function download(){const blob=new Blob([JSON.stringify({session,products,events},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='fabripass-demo-events.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Tracking export downloaded.')}
 if(!product)return null;

 return <div className="sales"><SalesHeader/><main className="sales-page"><div className="sales-kicker">FABRIPASS LIVE PROTOTYPE / SCAN & TRACK</div><h1>Give a garment<br/>its next checkpoint.</h1><p>Choose a sample product. Scan its QR with another phone. Confirm a check-in and watch it appear here.</p><div className="demo-note">Demonstration data only. Workspace products are copied here as sanitized sample records. Product photos are intentionally public in this demo; buyer names, supplier details, notes and evidence files stay private.</div><div className="demo-toolbar"><span className="live-indicator">{synced?'Last synced '+synced:'Connecting to shared tracking…'}</span><div className="sales-actions"><button className="sales-button" onClick={download} disabled={!loaded||!!error}><Download size={16}/>Export history</button><a className="sales-button" href="/demo"><RefreshCw size={16}/>New demo session</a></div></div>
  <div className="demo-products" role="group" aria-label="Choose a sample garment">{products.map(item=><button key={item.id} className={'demo-product '+(selected===item.id?'active':'')} aria-pressed={selected===item.id} onClick={()=>{setSelected(item.id);setNotice('')}}>{item.imageUrl?<img className="demo-product-thumb" src={item.imageUrl} alt=""/>:<Shirt size={32}/>}<span><strong>{item.name}</strong><small>{item.sku} · {item.category}{item.workspace?' · Workspace sample':''}</small></span></button>)}</div>
  <div className="demo-columns"><section className="demo-box"><div className="sales-kicker">{product.category} / {product.workspace?'WORKSPACE SAMPLE':'SAMPLE RECORD'}</div><h2>{product.name}</h2>{product.imageUrl&&<figure className="demo-image-stage"><img src={product.imageUrl} alt={product.name}/><figcaption>Workspace product image · visible in this public sample</figcaption></figure>}<dl className="product-facts">{[['Style / batch',product.sku+' / '+product.batch],['Composition',product.composition],['Manufactured in',product.origin],['Order quantity',product.quantity],['Fabric',product.weight],['Sample size / colour',product.size+' / '+product.color]].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><div className="qr-panel">{qr?<img src={qr} width={180} height={180} alt={'Scannable QR for '+product.name}/>:<p role="status">Preparing the QR…</p>}<div><h3>Open your phone camera.</h3><p>Scan this code, choose a checkpoint and confirm. This screen refreshes every five seconds.</p>{qr&&<a className="text-link" href={qr} download={selected+'-qr.png'}><Download size={16}/>Download QR label</a>}</div></div><div className="sales-actions"><a className="sales-button dark" href={link||'#'} aria-disabled={!link}>Open check-in <ArrowUpRight size={16}/></a><button className="sales-button" onClick={copy} disabled={!link}><Copy size={16}/>Copy link</button></div>{link&&<p className="qr-link">{link}</p>}{notice&&<p className="form-message" role="status">{notice}</p>}<p className="sales-micro">Save this dashboard URL to return to the same session. No personal details are required to check in.</p></section>
   <section className="demo-box"><div className="demo-toolbar"><h2>Tracking history</h2><span className="sales-kicker">{filtered.length} EVENTS</span></div><p className="sales-micro">For {product.sku} · newest first · times shown on this device</p>{error&&<p role="alert" className="error-panel">{error}</p>}{!loaded?<p role="status">Loading saved checkpoints…</p>:filtered.length?<ol className="tracking-list" aria-live="polite">{filtered.map(event=><li key={event.id}><span className="event-dot"/><div><strong>{event.checkpoint}</strong><time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time><p>{product.sku} · Demo check-in</p></div></li>)}</ol>:<div className="tracking-empty"><ScanLine size={32}/><h3>The next scan starts the story.</h3><p>No check-ins in this session yet. Scan the product QR and confirm a checkpoint to begin.</p></div>}<div className="demo-note"><strong>The sample handover</strong><br/>Factory QC → Packing → Dispatch → Buyer received<br/>Each selection records an event. Checkpoints can be repeated for demonstrations.</div><a href="/resources#demo" className="text-link">Read the two-device guide →</a></section></div>
 </main><SalesFooter/></div>;
}
