import {ArrowUpRight,BookOpenCheck,CheckCircle2,Database,Eye,FileCheck2,LockKeyhole,QrCode,Route,ScanLine,ShieldCheck,Sparkles} from 'lucide-react';
import {SalesHeader,SalesFooter} from '../sales/shell';
import PrintButton from './print-button';

export const metadata={title:'Buyer resources and user manual | FabriPass',description:'FabriPass product overview, data trust model, live QR demo guide, pilot plan and step-by-step garment traceability manual.'};

const readinessChecks=['Product identity and style code','Batch and production quantity','Manufacturing facility and country','Material composition totals 100%','Four supply-chain stages identified','Care and repair information','Reuse and end-of-life guidance','Current evidence internally reviewed'];

export default function Resources(){return <div className="sales"><SalesHeader/><main className="sales-page resources-page">
 <section className="resources-hero"><div><div className="sales-kicker">FABRIPASS / BUYER RESOURCE CENTRE</div><h1>See the record.<br/>Understand the evidence.<br/><em>Know the limits.</em></h1><p>A decision-ready guide for garment owners, sourcing teams and buyers evaluating the FabriPass workflow.</p><div className="sales-print"><a className="sales-button dark" href="/documents/FabriPass-Website-User-Manual.pdf" download>Download user manual PDF</a><PrintButton/><a href="/demo" className="sales-button">Open live demo <ArrowUpRight size={17}/></a></div></div><div className="resource-orbit" aria-hidden="true"><div className="orbit-core"><QrCode/><strong>SCAN</strong><small>shared product record</small></div><span className="orbit-node node-a"><Database/>Structured data</span><span className="orbit-node node-b"><FileCheck2/>Evidence context</span><span className="orbit-node node-c"><Route/>Checkpoints</span></div></section>

 <nav className="document-nav" aria-label="Resource sections">{['Overview','Workflow','Readiness','Pilot','Demo','Data','Privacy','Terms'].map(s=><a key={s} href={'#'+s.toLowerCase()}>{s}</a>)}</nav>

 <section className="resource-principles" aria-label="FabriPass key principles"><article><Eye/><span>BUYER VIEW</span><strong>Clear product facts, photo, QR and demo checkpoints</strong></article><article><LockKeyhole/><span>PRIVATE WORKSPACE</span><strong>Buyer names, suppliers, notes and evidence stay signed-in</strong></article><article><ShieldCheck/><span>TRUST BOUNDARY</span><strong>Readiness measures completeness, never certification</strong></article><article><ScanLine/><span>WORKING PROTOTYPE</span><strong>Phone check-ins are stored and shared across devices</strong></article></section>

 <div className="doc-grid">
  <section id="overview" className="doc-card wide resource-feature"><div><span className="sales-kicker">01 / PRODUCT OVERVIEW</span><h2>A connected garment record built for a better buyer conversation.</h2><p>FabriPass combines style and batch identity, declared composition, factory origin, care guidance, supply-stage references and supporting evidence in one working record. The workspace makes gaps visible before a buyer request arrives.</p><div className="important-callout"><Sparkles/><p><strong>Buyer value:</strong> a consistent record that can be inspected, exported and demonstrated. <strong>Factory value:</strong> less time reconstructing the same facts across repeated requests.</p></div></div><div className="resource-stack"><div><span>01</span><strong>Create</strong><small>Style and batch record</small></div><div><span>02</span><strong>Support</strong><small>Evidence and source context</small></div><div><span>03</span><strong>Review</strong><small>Eight visible readiness checks</small></div><div><span>04</span><strong>Share</strong><small>Sanitized demo and QR</small></div></div><table className="resources-table"><thead><tr><th>Audience</th><th>What they use</th><th>Decision signal</th></tr></thead><tbody>{[['Factory owner','Portfolio overview and readiness','Where product data work is blocked'],['Merchandising','Reusable product and batch records','Time to prepare comparable buyer packs'],['Compliance team','Linked evidence and review state','Which declarations still lack current support'],['Brand / importer','Consistent sample record and data export','Whether the agreed pilot pack is usable']].map(r=><tr key={r[0]}>{r.map(t=><td key={t}>{t}</td>)}</tr>)}</tbody></table></section>

  <section id="workflow" className="doc-card wide"><span className="sales-kicker">02 / WORKFLOW</span><h2>From internal record to public sample.</h2><div className="resource-timeline">{[['A','Create the product','Enter identity, batch, factory, materials and supply stages. Add an optional product photo.'],['B','Review the gaps','The dashboard calculates eight completeness checks and shows the next missing information.'],['C','Link evidence','Upload private PDFs or images, record expiry, and mark an internal review against the current product revision.'],['D','Open Live Demo','FabriPass copies a sanitized sample. Product photo, identity, composition, origin, quantity and care can appear; confidential fields do not.'],['E','Scan and check in','A second phone opens the product QR, confirms a checkpoint and updates the shared session history.']].map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>

  <section id="readiness" className="doc-card"><span className="sales-kicker">03 / READINESS MODEL</span><h2>Eight checks. Every gap visible.</h2><div className="readiness-list">{readinessChecks.map((check,index)=><div key={check}><CheckCircle2/><span>{check}</span><small>{String(index+1).padStart(2,'0')}</small></div>)}</div><div className="important-callout warning"><ShieldCheck/><p><strong>A 100% score means all eight fields are complete for internal review.</strong> It does not verify truth, legal conformity, product authenticity or certificate validity.</p></div></section>

  <section id="pilot" className="doc-card"><span className="sales-kicker">04 / PILOT PLAN</span><h2>Six weeks to an informed decision.</h2><p>Proposed scope: one factory, 25 style or batch records, three suppliers and one participating buyer. Final scope and commercial terms are agreed directly for each pilot.</p><ol className="pilot-weeks"><li><strong>Week 1 — Baseline</strong><span>Agree fields, record owners, access and three buyer requests.</span></li><li><strong>Week 2 — Prepare</strong><span>Map records, identify missing values and gather source evidence.</span></li><li><strong>Weeks 3–4 — Operate</strong><span>Train the team and review five representative records.</span></li><li><strong>Week 5 — Buyer review</strong><span>Test the record, QR flow and export pack.</span></li><li><strong>Week 6 — Decide</strong><span>Compare results and agree remaining production work.</span></li></ol><p><strong>Proposed targets:</strong> 90% agreed-field completeness and 30% lower median preparation time across comparable exercises. Results depend on source data and participation.</p><a className="text-link" href="/#pilot">Register pilot interest <ArrowUpRight size={16}/></a></section>

  <section id="demo" className="doc-card wide demo-guide"><div><span className="sales-kicker">05 / TWO-DEVICE DEMO</span><h2>Scan on one device. Watch on another.</h2><ol><li>Open <strong>Live demo</strong> on a laptop. The URL receives a new demo session ID.</li><li>Select a sample garment or your newest signed-in workspace product.</li><li>Scan the displayed QR with another phone, or copy the check-in link.</li><li>Choose Factory QC, Packing, Dispatch or Buyer received, then confirm.</li><li>Watch the laptop refresh within five seconds. Reload either device to confirm the history is saved.</li></ol></div><div className="demo-proof"><QrCode/><h3>What the demo proves</h3><ul><li>QR link resolution</li><li>Cross-device form submission</li><li>Durable checkpoint storage</li><li>Shared session history</li></ul><h3>What it does not prove</h3><ul><li>Identity or physical possession</li><li>GPS movement or shipment status</li><li>Origin, authenticity or certification</li></ul><a className="sales-button light" href="/demo">Run the demo <ArrowUpRight size={16}/></a></div></section>

  <section id="data" className="doc-card wide"><span className="sales-kicker">06 / DATA & TRUST MAP</span><h2>Know exactly what crosses the boundary.</h2><div className="data-boundary"><article><Eye/><h3>Visible in the sanitized Live Demo</h3><ul><li>Product name, style code and batch</li><li>Category, composition and origin</li><li>Quantity and care instructions</li><li>Optional product photo</li><li>Demo session checkpoint events</li></ul></article><article><LockKeyhole/><h3>Kept inside the signed-in workspace</h3><ul><li>Buyer assignment</li><li>Facility and supplier identities</li><li>Internal notes</li><li>Evidence files and review details</li><li>Full private workspace activity</li></ul></article></div><p className="resource-footnote">Product photos are the deliberate exception: when a workspace user uploads one, the form clearly identifies it as public in the Live Demo. Never upload confidential artwork.</p></section>

  <section id="privacy" className="doc-card"><span className="sales-kicker">07 / PRIVACY & DATA USE</span><h2>Keep demo and factory data distinct.</h2><p>Anyone with a demo session link and Site access can view its checkpoint history and add sample events. Check-ins store product, checkpoint, event ID and server timestamp. The application does not request GPS location or a camera feed.</p><p>Private factory APIs require sign-in and scope records to the authenticated account. Uploaded evidence remains private. Uploaded product photos receive a public demo image URL so the sanitized record can display them.</p><p>Pilot inquiries store the submitted name, business email, company, role, message and time for a pilot discussion. No email is automatically sent.</p></section>

  <section id="terms" className="doc-card"><span className="sales-kicker">08 / PROTOTYPE TERMS</span><h2>Explore with clear expectations.</h2><p>Sample garment claims and checkpoints are illustrative or self-reported. FabriPass does not issue an EU conformity certificate and does not represent customer endorsements, measured customer savings or a service-level guarantee.</p><p>Do not use the prototype as the sole record for operational decisions. Agree access, security, backup, recovery, retention, support and applicable regulatory requirements before commercial onboarding.</p><p>Factory tenants, team roles, buyer invitations, ERP integrations, production identifiers and registry integration remain production scope to agree.</p></section>
 </div>
 <section className="resource-cta"><BookOpenCheck/><div><span className="sales-kicker">TAKE IT INTO THE MEETING</span><h2>Use the guide. Run the scan. Discuss the real workflow.</h2></div><a className="sales-button light" href="/documents/FabriPass-Website-User-Manual.pdf" download>Download manual</a></section>
 </main><SalesFooter/></div>}
