import {db,bucket,identity,json,fail,HttpError,originCheck,limitedBody,jsonBody} from '../lib';
import {expired,type Evidence} from '../../model';
export const dynamic='force-dynamic';
export async function POST(req:Request){try{originCheck(req);const user=await identity();const bytes=await limitedBody(req,11*1024*1024);const form=await new Response(bytes,{headers:{'Content-Type':req.headers.get('content-type')||''}}).formData();const file=form.get('file'),productId=String(form.get('productId')||''),kind=String(form.get('kind')||''),expires=String(form.get('expires')||'');
 if(!(file instanceof File)||!file.size)throw new HttpError(400,'Choose a PDF, PNG or JPEG document.');if(file.size>10*1024*1024)throw new HttpError(413,'Maximum file size is 10 MB.');
 if(!['Material test','Supplier declaration','Transaction certificate','Facility certificate','Other'].includes(kind))throw new HttpError(400,'Choose a valid evidence type.');if(expires&&(!/^\d{4}-\d{2}-\d{2}$/.test(expires)||!Number.isFinite(Date.parse(expires))||new Date(expires).toISOString().slice(0,10)!==expires))throw new HttpError(400,'Use a valid expiry date.');
 const store=db();const product=await store.prepare('SELECT id FROM products WHERE id=? AND owner=?').bind(productId,user.userId).first();if(!product)throw new HttpError(404,'Product not found.');
 const count=await store.prepare('SELECT COUNT(*) AS n FROM evidence WHERE owner=?').bind(user.userId).first<{n:number}>();if((count?.n||0)>=1000)throw new HttpError(400,'Pilot evidence capacity reached (1,000 documents).');
 const content=new Uint8Array(await file.arrayBuffer());const isPdf=new TextDecoder().decode(content.slice(0,5))==='%PDF-',isPng=content[0]===137&&content[1]===80&&content[2]===78&&content[3]===71,isJpg=content[0]===255&&content[1]===216&&content[2]===255;
 const mime=isPdf?'application/pdf':isPng?'image/png':isJpg?'image/jpeg':'';if(!mime||mime!==file.type)throw new HttpError(400,'File contents must match a PDF, PNG or JPEG file.');
 const id=crypto.randomUUID(),objectKey=user.userId+'/'+id,now=new Date().toISOString();const digest=await crypto.subtle.digest('SHA-256',content);const sha256=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');const name=file.name.replace(/[\u0000-\u001f\u007f]/g,'').slice(0,180)||'Evidence';
 const doc:Evidence={id,productId,name,kind,expires,status:'pending',uploadedAt:now,sha256,hasFile:true,sample:false};await bucket().put(objectKey,content,{httpMetadata:{contentType:mime}});
 try{await store.batch([store.prepare('INSERT INTO evidence(id,owner,product_id,payload,object_key) VALUES(?,?,?,?,?)').bind(id,user.userId,productId,JSON.stringify(doc),objectKey),store.prepare('INSERT INTO activity(id,owner,message,created_at,snapshot) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,'Uploaded evidence: '+name,now,JSON.stringify(doc))])}catch(e){await bucket().delete(objectKey);throw e}
 return json({evidence:doc},201);
 }catch(e){return fail(e)}}
export async function PATCH(req:Request){try{originCheck(req);const user=await identity();const body=await jsonBody(req);if(typeof body.id!=='string'||!['pending','reviewed'].includes(body.status))throw new HttpError(400,'Invalid review request.');const store=db();const row=await store.prepare('SELECT payload,product_id FROM evidence WHERE id=? AND owner=?').bind(body.id,user.userId).first<{payload:string;product_id:string}>();if(!row)throw new HttpError(404,'Evidence not found.');const doc=JSON.parse(row.payload) as Evidence;if(!doc.hasFile)throw new HttpError(400,'A sample reference cannot be reviewed. Upload the original document.');if(expired(doc)&&body.status==='reviewed')throw new HttpError(400,'Expired evidence cannot be marked current.');const product=await store.prepare('SELECT version FROM products WHERE id=? AND owner=?').bind(row.product_id,user.userId).first<{version:number}>();if(!product)throw new HttpError(404,'Product not found.');const updated={...doc,status:body.status,reviewer:body.status==='reviewed'?user.displayName:undefined,reviewedVersion:body.status==='reviewed'?product.version:undefined};const now=new Date().toISOString();await store.batch([store.prepare('UPDATE evidence SET payload=? WHERE id=? AND owner=?').bind(JSON.stringify(updated),body.id,user.userId),store.prepare('INSERT INTO activity(id,owner,message,created_at,snapshot) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),user.userId,(body.status==='reviewed'?'Internally reviewed: ':'Reopened review: ')+doc.name,now,JSON.stringify(updated))]);return json({evidence:updated});}catch(e){return fail(e)}}
