'use client';
import {useState,type FormEvent} from 'react';
import {ArrowUpRight,ArrowRight,ScanLine,FileCheck2,Route,Shirt,Check,Layers3} from 'lucide-react';
import {SalesHeader,SalesFooter} from './shell';
export default function Landing(){
const [state,setState]=useState('');const [busy,setBusy]=useState(false);const [failed,setFailed]=useState(false);
async function inquire(e:FormEvent<HTMLFormElement>){
e.preventDefault();const form=e.currentTarget;setBusy(true);setState('');setFailed(false);
try{const r=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const out=await r.json() as {reference:string;error?:string};if(!r.ok)throw Error(out.error||'Unable to save. Please retry.');setState('Inquiry saved. Reference '+out.reference+'. Keep this reference for your pilot discussion. No automatic email is sent by this prototype.');form.reset()}catch(e){setFailed(true);setState(e instanceof Error?e.message:'Unable to save. Please retry.')}finally{setBusy(false)}
}
return <div className="sales"><a className="skip-link" href="#main">Skip to content</a><SalesHeader/><main id="main">
<section className="sales-hero"><div><div className="sales-kicker">GARMENT INTELLIGENCE, FROM SOURCE TO SCAN</div><h1>Your garments.<br/>Their journey.<br/><em>One clear record.</em></h1><p className="sales-lede">Turn scattered factory information into a product story buyers can inspect. Connect materials, evidence and checkpoints to a QR on every garment record.</p><div className="sales-actions"><a className="sales-button dark" href="/demo">Try scan & track <ArrowUpRight size={18}/></a><a className="sales-button" href="/resources">Explore the buyer pack <ArrowRight size={18}/></a></div><p className="sales-micro">For garment factories, sourcing teams and brands.</p></div><a className="hero-record" href="/demo" aria-label="Explore the cotton tee in the live demo"><div className="record-top"><span>LOOMPASS / PRODUCT RECORD</span><ArrowUpRight size={21}/></div><div className="garment-display"><Shirt size={152} strokeWidth={.8}/><span>01 / 03</span></div><div className="record-bottom"><div className="sales-kicker">KNITWEAR · BANGLADESH</div><h2>Everyday cotton tee</h2><p>LP-TEE-001 / Batch BD-2609-01</p><div className="record-pills"><span>100% cotton</span><span>180 GSM</span><span>Sample record</span></div></div><div className="record-scan"><ScanLine/><span>Open. Scan. Record a checkpoint.</span><ArrowRight size={18}/></div></a></section>
<div className="audience-strip"><span>DESIGNED FOR THE PEOPLE BEHIND THE GARMENT</span><strong>Factory owners</strong><strong>Merchandisers</strong><strong>Compliance teams</strong><strong>Global buyers</strong></div>
<section id="platform" className="sales-section"><div className="section-intro"><div><div className="sales-kicker">01 / THE PLATFORM</div><h2>Less chasing documents.<br/>More clarity on every order.</h2></div><p>A consistent product record helps your team answer buyer questions with context, supporting evidence and a clear view of what still needs work.</p></div><div className="feature-grid">{[{icon:Layers3,title:'One product record',body:'Keep style, batch, fibre composition, origin and care information together. Know which version the team is reviewing.'},{icon:FileCheck2,title:'Evidence with context',body:'Attach documents to the product they support. Track expiry and internal review status before preparing a buyer pack.'},{icon:Route,title:'A visible journey',body:'Map suppliers and processing stages. Record sample QC, packing, dispatch and receipt checkpoints in the live prototype.'},{icon:ScanLine,title:'A scan that connects',body:'Generate a product QR, open it on another phone and submit a demo check-in. See the event appear in the tracking history.'}].map(x=><article key={x.title}><x.icon size={26}/><h3>{x.title}</h3><p>{x.body}</p></article>)}</div></section>
<section className="scenario-section"><div><div className="sales-kicker">02 / A GARMENT SCENARIO</div><h2>From the factory floor<br/>to the buyer’s hands.</h2><p>Imagine a cotton tee order leaving Gazipur. Quality control checks the batch, packing confirms the handover, dispatch records the shipment, and the buyer checks in on receipt.</p><p>Use two devices to see the handover happen. Each submitted event is saved with its product, checkpoint and server timestamp.</p><a href="/demo" className="sales-button light">Follow the sample order <ArrowUpRight size={18}/></a></div><ol className="scenario-steps">{['Create the garment record','Generate the product QR','Scan and confirm a checkpoint','Watch the tracking history update'].map((s,i)=><li key={s}><span>0{i+1}</span><strong>{s}</strong><ArrowRight size={20}/></li>)}</ol></section>
<section className="sales-section"><div className="section-intro"><div><div className="sales-kicker">03 / THE BUYER CONVERSATION</div><h2>Give the next meeting<br/>something real to work with.</h2></div><a className="text-link" href="/resources">Open all resources <ArrowUpRight size={18}/></a></div><div className="resource-teasers">{[['01','Product overview','Who uses LoomPass, how the workflow fits and what is available today.'],['02','Pilot implementation plan','A six-week proposal with owners, milestones and acceptance measures.'],['03','Data & trust brief','Public demo data, private records and the limits of a scan.']].map(([n,t,d])=><a href="/resources" key={n}><span>{n} / BUYER DOCUMENT</span><h3>{t}</h3><p>{d}</p><ArrowUpRight size={22}/></a>)}</div></section>
<section id="plans" className="sales-section plans-section"><div className="section-intro"><div><div className="sales-kicker">04 / START SMALL. PROVE THE VALUE.</div><h2>A pilot first.<br/>A subscription when it fits.</h2></div><p>Proposed commercial packages in USD. Final scope, production controls and terms are agreed before purchase. No payment is collected here.</p></div><div className="plan-grid">{[{name:'Design partner',price:'$1,500',unit:'proposed / six-week pilot',items:['One factory, 25 style/batch records','Source-data mapping and training','Buyer feedback and outcome report'],cta:'Discuss the pilot'},{name:'Factory',price:'$399',unit:'proposed / month',items:['300 active product records','Proposed team access for ten users','5 GB evidence storage'],cta:'Request Factory scope'},{name:'Group',price:'$899',unit:'proposed / month',items:['Up to three manufacturing sites','1,500 active product records','Proposed team access for 25 users'],cta:'Request Group scope'}].map((p,i)=><article key={p.name} className={i===0?'featured':''}><span className="sales-kicker">{p.name}</span><h3>{p.price}</h3><p>{p.unit}</p><ul>{p.items.map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><a href="#pilot" className={'sales-button '+(i===0?'dark':'')}>{p.cta}<ArrowUpRight size={16}/></a></article>)}</div><p className="sales-micro">Team roles, factory tenants, billing and enterprise integrations are proposed production scope. The prototype supports individual workspaces and shared sample tracking. Taxes, physical labels and external verification are excluded.</p></section>
<section className="sales-section faq-section"><div><div className="sales-kicker">05 / BEFORE YOU START</div><h2>Clear answers.<br/>A practical next step.</h2></div><div>{[['Does the QR really work?','Yes. Each demo QR opens a product check-in page for your session. Another device can record an event, and the dashboard refreshes the shared history. Visitors must have access to the Site.'],['Does a scan prove authenticity?','No. A check-in is a submitted event. It does not prove physical possession, certify origin or provide GPS tracking. Production claims need independently reviewed evidence.'],['Can we upload factory documents?','The signed-in workspace supports private evidence uploads and per-user product records. Agree production security, retention and access requirements before introducing confidential data.'],['Is this an EU compliance certificate?','No. LoomPass structures records and identifies information gaps. Applicable requirements, verification and registry integration need separate assessment.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<section id="pilot" className="pilot-section"><div><div className="sales-kicker">LET’S MAKE THE NEXT ORDER CLEARER</div><h2>Bring one factory.<br/>One buyer.<br/>One real use case.</h2><p>Tell us what you want to trace. Start with an agreed scope and measurable outcomes.</p><a className="text-link" href="/resources#pilot">Read the pilot plan <ArrowUpRight size={18}/></a></div><form onSubmit={inquire}><h3>Register pilot interest</h3><label>Your name<input name="name" required maxLength={100} autoComplete="name"/></label><label>Work email<input type="email" name="email" required maxLength={200} autoComplete="email"/></label><label>Company<input name="company" required maxLength={150} autoComplete="organization"/></label><label>Your role<select name="role"><option>Factory owner / management</option><option>Buyer / sourcing team</option><option>Merchandising / operations</option><option>Compliance / sustainability</option></select></label><label>What would you like to trace?<textarea name="message" required maxLength={1500} rows={3}/></label><label className="consent"><input type="checkbox" name="consent" value="yes" required/>I agree to the <a href="/resources#privacy">inquiry data use</a>.</label><button className="sales-button dark" disabled={busy}>{busy?'Saving inquiry…':'Save pilot inquiry'}<ArrowRight size={17}/></button><p className="sales-micro">Saved for a pilot discussion. This prototype does not send email or book meetings.</p>{state&&<p role={failed?'alert':'status'} className="form-message">{state}</p>}</form></section>
</main><SalesFooter/></div>}

